// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.Order;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.io.IOException;
import java.util.*;

@TestMethodOrder(OrderAnnotation.class)
public class SeleniumTests {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() throws IOException {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Order(1)
  public void registerNewUserAndLogin() {
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.linkText("Реєстрація")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("mockUser1");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("mockUser1");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("mockEmail1@gmail.com");
    driver.findElement(By.id("secretQuestion")).click();
    driver.findElement(By.id("secretQuestion")).sendKeys("Favourite singer");
    driver.findElement(By.id("secretAnswer")).click();
    driver.findElement(By.id("secretAnswer")).sendKeys("Adele");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("mockUser1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mockUser1");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".btn-link")).click();
  }

  @Test
  @Order(2)
  public void resetUserPassword() {
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.linkText("Забули пароль?")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mockEmail1@gmail.com");
    driver.findElement(By.name("answer")).click();
    driver.findElement(By.name("answer")).sendKeys("Adele");
    driver.findElement(By.name("newPassword")).click();
    driver.findElement(By.name("newPassword")).sendKeys("mockUser3");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("mockUser1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mockUser3");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("body")).click();
  }

  @Test
  @Order(3)
  public void userCreatesPost() {
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("mockUser1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mockUser3");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Новий пост")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("I don\'t like");
    driver.findElement(By.id("content")).click();
    driver.findElement(By.id("content")).sendKeys("Doing this lab to be honest...");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > a")).click();
  }

  @Test
  @Order(4)
  public void userWritesCommentUnderThePost() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("mockUser1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mockUser3");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > a")).click();
    driver.findElement(By.id("content")).click();
    driver.findElement(By.id("content")).sendKeys("Bro, I can\'t do nothing but agree with ya");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) > p:nth-child(2)")).click();
  }

  @Test
  @Order(5)
  public void userHasProfile() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("mockUser1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mockUser3");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Профіль")).click();
    driver.findElement(By.linkText("Редагувати профіль")).click();
    driver.findElement(By.id("fullName")).click();
    driver.findElement(By.id("fullName")).sendKeys("Daniil Horbenko");
    driver.findElement(By.id("bio")).click();
    driver.findElement(By.id("bio")).click();
    driver.findElement(By.id("bio")).sendKeys("Just a SUMDU student who hates doing this lab");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("p:nth-child(4) > strong")).click();
    driver.findElement(By.cssSelector("p:nth-child(5) > strong")).click();
    driver.findElement(By.cssSelector("p:nth-child(3) > strong")).click();
    driver.findElement(By.cssSelector("p:nth-child(2) > strong")).click();
    driver.findElement(By.cssSelector("h2")).click();
  }
}
